ENH: Add switch for trigger data format #5
SiLab-Bonn/pyBAR_fei4_interpreter pull request #6
Opened 2016-11-30 10:49 UTC by YannickDieter

2016-11-30 12:25 UTC, DavidLP requested changes

2016-11-30 12:25 UTC, DavidLP commented on pybar_fei4_interpreter/Interpret.cpp
> +void Interpret::setTriggerFormat(const char* rTriggerFormat)
`const char*` is C-style code and not a modern way of writing C/C++ code. You should use a [std::string](http://www.cplusplus.com/reference/string/string/)

2016-11-30 12:25 UTC, DavidLP commented on pybar_fei4_interpreter/Interpret.cpp
> +	_TriggerFormat = "COMBINED";
I would prefer to have a number indicating the mode instead of a character array.

2016-11-30 12:25 UTC, DavidLP commented on pybar_fei4_interpreter/defines.h
> +#define TRIGGER_NUMBER_MASK_M26		0x0000FFFF //trigger number of M26
This is not for Mimosa only, but a mode that can be generally chosen. So we should rename

2016-11-30 12:25 UTC, DavidLP commented on pybar_fei4_interpreter/defines.h
> +#define TRIGGER_TIME_STAMP_MASK_M26		0x7FFF0000 //time stamp of M26
Other name please

2016-11-30 12:25 UTC, DavidLP commented on pybar_fei4_interpreter/Interpret.cpp
> +	std::cout << "# Trigger Format    " << std::right << std::setw(15) << _TriggerFormat << "\n";
Good

2016-11-30 14:04 UTC, DavidLP commented
Can you push against development? Better to keep the master more stable.

2016-11-30 14:08 UTC, laborleben commented
Can you add defines for the different modes?
```
#define MODE_NAME 0
...
```

2016-11-30 19:04 UTC, YannickDieter commented on pybar_fei4_interpreter/defines.h
> +#define TRIGGER_TIME_STAMP_MASK_M26		0x7FFF0000 //time stamp of M26
Renaming: 
`#define TRIGGER_NUMBER_MASK		0x7FFFFFFF //trigger number is in the low word`
`#define TRIGGER_TIME_STAMP_MASK		0x7FFFFFFF //trigger number is in the low word`
`#define TRIGGER_NUMBER_MASK_COMBINED		0x0000FFFF //trigger number in combined mode`
`#define TRIGGER_TIME_STAMP_MASK_COMBINED		0x7FFF0000 //time stamp in combined mode`

2016-11-30 19:04 UTC, YannickDieter commented on pybar_fei4_interpreter/Interpret.cpp
> +	_TriggerFormat = "COMBINED";
So instead of comparing two strings with `if _(strcmp(_TriggerFormat, "COMBINED") == 0)`, you would like to have a comparison with a number which indicates the trigger mode?
This was also my idea, but Jens said that it would be better if I indicate the modes with strings.

2016-12-19 12:20 UTC, DavidLP commented
Bump, any progress?

2017-01-02 10:25 UTC, YannickDieter commented
I will work on it this week

2017-01-02 16:03 UTC, YannickDieter commented
Updates are pushed. I included defines for the different trigger modes and compare them instead of the characters before.

2017-01-04 08:55 UTC, laborleben commented
You are still pushing to master. You need to push against development branch.

2017-01-04 10:59 UTC, YannickDieter commented
Oh sorry! Is it necessary to create a new pull request if I want to push against development branch? Because at the moment I cannot push against development.

2017-01-04 11:13 UTC, laborleben commented
It is probably better if you create a new upstream branch. Then you can use github to create the pull request.

2017-01-04 11:58 UTC, YannickDieter commented
Sorry, I am new to git. What do you mean with this?

2017-01-04 15:18 UTC, laborleben commented
https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches

The branch name should be related to the changes, e.g. trigger_mode_support

2017-01-05 11:27 UTC, closed without merging

2017-01-05 11:29 UTC, laborleben commented
This was closed in favor of the new pull request from trigger_data_format branch into development branch.